name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    name: update documentation on github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - uses: actions/cache@v3
        with:
          key: mkdocs-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          path: .cache

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install .[docs]
      - name: build and deploy documentation
        run: mkdocs gh-deploy --force

      - name: deployment summary
        run: echo "✅ Documentation deployed successfully!" >> $GITHUB_STEP_SUMMARY
