name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - tickersnap/**
      - tests/**
      - pyproject.toml
  push:
    branches: [main]

jobs:
  code-format:
    name: Check code format using black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
  
  lint:
    name: Check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e ".[dev]"
      - name: Run ruff linting
        run: ruff check .
  
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e ".[dev]"
      - name: Run unit tests
        run: pytest -v tests/ -m "not integration"

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e ".[dev]"
      - name: Run integration tests
        run: pytest -v tests/ -m integration
        # continue on failure since integration tests depend on external APIs
        continue-on-error: true
