name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - tickersnap/**
      - pyproject.toml

jobs:
  code-format:
    name: check code format using black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
  
  lint:
    name: check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  
  unit-tests:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U pip
          pip install -e ".[dev]"
          pytest -s tests/
